### PR TITLE
Add enterprise boundaries

### PR DESCRIPTION
**Pull request by coldacid**
Adds `Enterprise_Boundary(e_alias)` for dashed-border rectangle. This matches the boundary style shown in _Software Architecture for Developers_ vol. 2.

Adds `Enterprise_Boundary(e_alias, e_label)` for standard boundary shape. This uses the `package` shape and includes a label, similar to the boundaries in PR #1.

### CODE REVIEW

**Comment by RicardoNiepel** [comment]
- Do we really need two boundary styles?
- Shouldn't all boundaries have a label? Even for a specialized enterprise context diagram it could be a enterprise, BU, devision or department boundary

**Comment by coldacid** [comment]
We probably don't need two styles, but I think it's best to have the option to match the style shown in Simon Brown's books. But yeah, there should be a label on both.

**Comment by RicardoNiepel** [comment]
If you find a solution for a dashed-border with label, I'm happy to merge it as the default boundary.

**Comment by coldacid** [comment]
Yep, not a problem.

**Comment by coldacid** [comment]
I just replaced the original branch with a new one that fits in better with the updated master branch.

**Comment by RicardoNiepel** [comment]
Thanks a lot - great addition!

**Pull request merged**
