### PR TITLE
plantuml version 1.2019.6

### PR DESCRIPTION
**Pull request by adrianvlupu**
Hi,
PlantUML was updated to version 1.2019.6 and some preprocessor directives changed. This causes the online generation of diagrams to fail.

From the [PlantUML page](http://plantuml.com/preprocessing)
>- You should not use !define and !definelong anymore. 
>- Use !function and variable definition instead !include allows now multiple inclusions : you don't have to use !include_many anymore
>- !include now accept URL, so you don't need !includeurl
>- Some features (like %date%) have been replaced by builtin functions (for example %date())
>- When calling a legacy !definelong macro with no arguments, you do have to use parenthesis. That is you have to use my_own_definelong() because my_own_definelong without parenthesis is not recognized by the new preprocessor.

I updated the repository to use `!function` instead of `!define`.
I updated the README files and regenerated some sample images that broke.

### CODE REVIEW

**Comment by coldacid** [comment]
Do the original preprocessor directives still work on 1.2019.6? These are definitely breaking changes that if brought in would break C4-PlantUML for anyone still using older versions of PlantUML for whatever reason.

**Comment by adrianvlupu** [comment]
The original preprocessor directives still work. You can still use `!define` but when calling it you have to add `LAYOUT_WITH_LEGEND()`. They recommend not using them anymore

**Comment by adrianvlupu** [comment]
vscode-plantuml updated to v2.11.1 using the latest plantuml jar (https://github.com/qjebbs/vscode-plantuml/commit/ed9b9c582a9f1a58cd1a794ac3b3858f47095a6e).

The chocolatey package also got updated (https://chocolatey.org/packages/plantuml)

I guess it's safe to add this to a release/1-1 or something else branch.
If you guys want me to change anything let me know.

**Comment by adrianvlupu** [comment]
Sorry for spamming this PR, but apparently one line functions like
`!function LAYOUT_TOP_DOWN() return top to bottom direction`
or the classic
`!define LAYOUT_TOP_DOWN() top to bottom direction`
don't actually require `()` when calling. Only multi-line functions or defines need to be called like this.

I also had a legend bug in my PR. If an include uses a global variable with `$` the include that includes it needs to reference the variable without it.

**Pull request closed without merging**
