### PR TITLE
Fix erro in exemple plantUML

### PR DESCRIPTION
**Pull request by filipe-crespo**
Add `()` in call the methods.

### CODE REVIEW

**Comment by jd-porter** [comment]
Fixes #23, verified working in VSCode PUML extension! 👍

**Comment by solongtony** [comment]
Is this going to be merged?  The examples don't work without it.

**Comment by anb0s** [comment]
It looks like this project is not maintained anymore. Lot of pull request are there but no comment from @RicardoNiepel and the last commit is from January 2019.

@adrianvlupu i and my colleagues have used your version and also other changes. Thanks! It looks like you are the most active maintainer and it would be perfect if your fork can be detached to own repository and be the new widely used version :)

**Comment by RicardoNiepel** [comment]
Thanks for feedback - needed to prioritize a lot of things.
I have already blocked next week to work through all PRs and will think about giving other maintainers access to it.

**Comment by anb0s** [comment]
> Thanks for feedback - needed to prioritize a lot of things.
> I have already blocked next week to work through all PRs and will think about giving other maintainers access to it.

Any news about integration of PRs or other maintainer access?

**Pull request closed without merging**
